### ISSUE TITLE
Crash on newest create version v0.5.1a

### ISSUE THREAD

**Issue by BugmanBugman** [EDToaster/LittleContraptions#17]

**Comment by SigmaFlame** [comment]
https://pastebin.com/GSbv0zhG

**Comment by muradakh** [comment]
We are aware of this, LC will need to be updated your the new create version. The update is coming soon 
#16

**Comment by EDToaster** [comment]
Fixed by #19

**Comment by Numilani** [comment]
Can this bugfix be backported to 1.18.2 releases? This issue appears to still occur (using Create 0.5.1.b) on 1.18.
